### ISSUE TITLE
kotlin  asm

### ISSUE THREAD

**Issue by JinYanjie** [sleticalboy/AutoTrack#1]
你好，在使用asm埋点的时候，您是怎么处理kotlin文件的？因为我的项目都是使用kotlin写的，在使用的时候发现没法将代码插入其中，不知道你怎么处理的？

**Comment by sleticalboy** [comment]
> 你好，在使用asm埋点的时候，您是怎么处理kotlin文件的？因为我的项目都是使用kotlin写的，在使用的时候发现没法将代码插入其中，不知道你怎么处理的？

kt 文件经过 kotlinc 编译后也是字节码文件，ASM 也是可以处理的
